version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    expose:
      - 3306
      - 33060
  app:
    depends_on:
      - mysql
    image: docker.io/sherifemad21/example:node
    ports:
      - 3000:3000
